// Autogenerated from Pigeon (v16.0.5), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// Generated class from Pigeon that represents data sent in messages.
struct Message {
  var text: String

  static func fromList(_ list: [Any?]) -> Message? {
    let text = list[0] as! String

    return Message(
      text: text
    )
  }
  func toList() -> [Any?] {
    return [
      text
    ]
  }
}
private class BcmHostApiCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 128:
      return Message.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class BcmHostApiCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? Message {
      super.writeByte(128)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class BcmHostApiCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return BcmHostApiCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return BcmHostApiCodecWriter(data: data)
  }
}

class BcmHostApiCodec: FlutterStandardMessageCodec {
  static let shared = BcmHostApiCodec(readerWriter: BcmHostApiCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol BcmHostApi {
  func showToast(msg: Message) throws -> Bool
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class BcmHostApiSetup {
  /// The codec used by BcmHostApi.
  static var codec: FlutterStandardMessageCodec { BcmHostApiCodec.shared }
  /// Sets up an instance of `BcmHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: BcmHostApi?) {
    let showToastChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.bcm_native_toast.BcmHostApi.showToast", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      showToastChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let msgArg = args[0] as! Message
        do {
          let result = try api.showToast(msg: msgArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      showToastChannel.setMessageHandler(nil)
    }
  }
}
